# Generated by Django 5.1.3 on 2024-12-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_task_description_remove_task_title_task_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='title',
        ),
    ]
